### ISSUE TITLE
Installing Python 3.9 on a Raspberry PI easy solution

### ISSUE THREAD

**Issue by tvdsluijs** [tvdsluijs/itheo#40]
https://itheo.nl/install-python-3-9-on-raspberry-pi/ 

 Installing python 3.9 on a Raspberry Pi in a few lines of code in easy to follow solution in a few steps. Finally Python 3.9 on a Raspberry PI

**Comment by Celinium** [comment]
Hi. Perfect timing, I just received a Pi and I was looking to update Python from 2.x to 3.9. I went through all the steps and after this command: 
sudo make altinstall
I received the following warning messages:
Installing collected packages: setuptools, pip
  WARNING: The script easy_install-3.9 is installed in '/usr/local/opt/python-3.9.0/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pip3.9 is installed in '/usr/local/opt/python-3.9.0/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-20.2.3 setuptools-49.2.1

**Comment by tvdsluijs** [comment]
> @Celinium

Hi Celinium, I did not receive this error on my PI. However I installed 3.8 on it some time ago so that might change stuff. It is a warning and not a error so you still might be able to run Python 3.9 following my steps. Could you please let me know if you get th

**Comment by tvdsluijs** [comment]
> @Celinium

if you do:
```shell
PATH=$PATH:/usr/local/opt/python-3.9.0/bin
```

in your terminal, you should be okay!

**Comment by Celinium** [comment]
Yes everything is working. Thank you@tvdsluijs for the follow-up and for the article.

> @tvdsluijs
> > @Celinium
> 
> if you do:
> ```shell
> PATH=$PATH:/usr/local/opt/python-3.9.0/bin
> ```
> 
> in your terminal, you should be okay!
> 
>

**Comment by derekboase** [comment]
Great article, thank you so much!

**Comment by roymcdio** [comment]
Hello and thanks for the great info. my comment is I see you used the                                                                                                          
 ./configure --prefix=/usr/local/opt/python-3.9.0                                                                           
instead of                                                                                                                
./configure --prefix=/usr/bin/python3.9                                                               
is there any reson for that?

**Comment by ttscotchtape** [comment]
Hi, thanks for this article! in 'nano~/.bashrc' I am not able to find the 'alias python' line. I'm using python 3.7 instead of 3.8. Should I just add the 'alias python=/usr/local/opt/python-3.9.0/bin/python3.9' in the last line anyway?

**Comment by tvdsluijs** [comment]
> @roymcdio
 well some linux systems seem to place it just a bit different. I upgraded from 3.8 to 3.9 so I guess that is where is differs.

**Comment by tvdsluijs** [comment]
> @ttscotchtape
> Hi, thanks for this article! in 'nano~/.bashrc' I am not able to find the 'alias python' line. I'm using python 3.7 instead of 3.8. Should I just add the 'alias python=/usr/local/opt/python-3.9.0/bin/python3.9' in the last line anyway? 

It could be that there is no alias line at all. Just add it at the end of the file. And you will be fine I guess

**Comment by fcreinhart** [comment]
Thank you for the article. Python 3.9.2 appears to be installed and running, but the first program I ran will not import RPi.GPIO. When I switch back to 3.7, everything is fine. I suspect there is a path problem. Any suggestions?

    import cmd, time, signal, RPi.GPIO as GPIO    #                    Monitor.PY 02-24-21
ModuleNotFoundError: No module named 'RPi'

**Comment by tvdsluijs** [comment]
> @fcreinhart
 Goodmorning! A few things could be happening here. Are your working in an environment? If yes things will be mixed up and you have to create a new environment and do a `pip install GPIO` or when you have a requirements file `pip install -r requirements.txt`. But it could also that you have installed the GPIO underneath the global 3.7 environment so when using the 3.9.x version a `pip install GPIO` would also solve the problem.

Let me know if it helped. Thank you!

**Comment by guljanjua** [comment]
Hi,

I have same issue. I have install python 3.8 on raspberry pi zero using this tutorial [https://itheo.tech/install-python-3-8-on-a-raspberry-pi/](url) but RPi.GPIP is working with python 3.7 not with python 3.8.

My python -V is 3.8
and python3 -V 3.7

I have read on a forum it is related to environment and paths but not sure how to solve this. Can anyone help please?

**Comment by tvdsluijs** [comment]
Hi Guljanjua, Have you seen my new post on Python on a Raspberry Pi?
https://itheo.tech/ultimate-python-installation-on-a-raspberry-pi-ubuntu-script/

You could install 3.8 with one single line of code

`wget -qO - https://raw.githubusercontent.com/tvdsluijs/sh-python-installer/main/python.sh | sudo bash -s 3.8.0`

**Comment by guljanjua** [comment]
Hi,

Thank you so much for your reply. Installing python is fine but RPi GPIO is not working on raspberry pi. Can you help in that?
